<?php
require_once __DIR__ . '/../config/modulos.php';
require_once __DIR__ . '/DteDataService.php';

class ModulePreferenceService {

    private const TABLE_NAME = 'dte_user_module_preferences';

    private const DOCUMENT_TYPES = [
        '01' => 'Factura',
        '03' => 'Crédito Fiscal',
        '05' => 'Nota de Crédito',
        '06' => 'Nota de Débito',
        '14' => 'Comprobante de Retención',
    ];

    private const DOCUMENT_TYPE_CLASSES = [
        '01' => 'is-invoice',
        '03' => 'is-tax-credit',
        '05' => 'is-credit-note',
        '06' => 'is-debit-note',
        '14' => 'is-retention',
    ];

    public static function ensureTable(PDO $pdo): void {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS " . self::TABLE_NAME . " (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                module_key VARCHAR(80) NOT NULL,
                preferences_json JSONB NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uniq_user_module_preferences UNIQUE (user_id, module_key)
            )"
        );
    }

    public static function getModuleColumnConfig(PDO $pdo, string $moduleKey, int $userId, ?array $module = null): array {
        self::ensureTable($pdo);

        $module = $module ?? getLibroModule($moduleKey) ?? ['columnas' => []];
        $default = self::getDefaultColumnConfig($moduleKey, $module);
        $stored = self::getStoredPreferences($pdo, $moduleKey, $userId);

        if ($stored === null) {
            return $default;
        }

        return self::normalizePreferences($moduleKey, $module, $stored, $default, true);
    }

    public static function getDefaultColumnConfig(string $moduleKey, array $module): array {
        $columnKeys = array_keys($module['columnas'] ?? []);
        $tableColumns = [];
        $excelColumns = [];

        foreach ($columnKeys as $columnKey) {
            $visibleByDefault = true;
            if ($moduleKey === 'compras' && in_array($columnKey, [
                'documento_relacionado_numero',
                'documento_relacionado_codigo',
                'documento_relacionado_fecha',
            ], true)) {
                $visibleByDefault = false;
            }

            $tableColumns[$columnKey] = $visibleByDefault;
            $excelColumns[$columnKey] = $visibleByDefault;
        }

        return [
            '_customized' => false,
            'table_columns' => $tableColumns,
            'excel_columns' => $excelColumns,
            'document_types' => self::defaultDocumentTypes($moduleKey),
        ];
    }

    public static function save(PDO $pdo, string $moduleKey, int $userId, array $payload, ?array $module = null): array {
        self::ensureTable($pdo);

        $module = $module ?? getLibroModule($moduleKey) ?? ['columnas' => []];
        $default = self::getDefaultColumnConfig($moduleKey, $module);
        $preferences = self::normalizePreferences($moduleKey, $module, $payload, $default, true);
        $preferences['_customized'] = true;

        $json = json_encode($preferences, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        if ($json === false) {
            throw new RuntimeException('No se pudo serializar la configuracion.');
        }

        $stmt = $pdo->prepare(
            "INSERT INTO " . self::TABLE_NAME . " (user_id, module_key, preferences_json)
             VALUES (:user_id, :module_key, :preferences_json)
             ON CONFLICT (user_id, module_key) DO UPDATE
             SET preferences_json = EXCLUDED.preferences_json,
                 updated_at = CURRENT_TIMESTAMP"
        );
        $stmt->execute([
            ':user_id' => $userId,
            ':module_key' => self::normalizeModuleKey($moduleKey),
            ':preferences_json' => $json,
        ]);

        return $preferences;
    }

    public static function restoreDefault(PDO $pdo, string $moduleKey, int $userId, ?array $module = null): array {
        self::ensureTable($pdo);

        $stmt = $pdo->prepare(
            "DELETE FROM " . self::TABLE_NAME . " WHERE user_id = :user_id AND module_key = :module_key"
        );
        $stmt->execute([
            ':user_id' => $userId,
            ':module_key' => self::normalizeModuleKey($moduleKey),
        ]);

        return self::getDefaultColumnConfig($moduleKey, $module ?? getLibroModule($moduleKey) ?? ['columnas' => []]);
    }

    public static function hasCustomPreferences(PDO $pdo, string $moduleKey, int $userId): bool {
        self::ensureTable($pdo);

        $stmt = $pdo->prepare(
            "SELECT 1 FROM " . self::TABLE_NAME . " WHERE user_id = :user_id AND module_key = :module_key LIMIT 1"
        );
        $stmt->execute([
            ':user_id' => $userId,
            ':module_key' => self::normalizeModuleKey($moduleKey),
        ]);

        return (bool) $stmt->fetchColumn();
    }

    public static function shouldShowColumn(array $preferences, string $columnKey, string $context): bool {
        $bucket = $context === 'excel' ? 'excel_columns' : 'table_columns';
        $columns = is_array($preferences[$bucket] ?? null) ? $preferences[$bucket] : [];

        return array_key_exists($columnKey, $columns) ? (bool) $columns[$columnKey] : true;
    }

    public static function filterColumns(array $columns, array $preferences, string $context): array {
        return array_values(array_filter($columns, static function ($columnKey) use ($preferences, $context): bool {
            return self::shouldShowColumn($preferences, (string) $columnKey, $context);
        }));
    }

    public static function filterColumnMap(array $columns, array $preferences, string $context): array {
        $filtered = [];
        foreach ($columns as $key => $label) {
            if (self::shouldShowColumn($preferences, (string) $key, $context)) {
                $filtered[$key] = $label;
            }
        }

        return $filtered;
    }

    public static function getDocumentTypeLabelForModule(string $moduleKey, string $tipoDte, array $preferences, string $fallback = ''): string {
        $tipoDte = self::normalizeTipoDte($tipoDte);
        if ($tipoDte === '') {
            return $fallback;
        }

        $typeConfig = self::getDocumentTypeConfig($preferences, $tipoDte);
        if ($typeConfig === null) {
            return $fallback;
        }

        return !empty($typeConfig['show']) ? (string) ($typeConfig['label'] ?? $fallback) : '';
    }

    public static function shouldHighlightDocumentType(string $moduleKey, string $tipoDte, array $preferences): bool {
        $typeConfig = self::getDocumentTypeConfig($preferences, self::normalizeTipoDte($tipoDte));
        return $typeConfig !== null && !empty($typeConfig['highlight']);
    }

    public static function documentTypeClass(string $tipoDte): string {
        $tipoDte = self::normalizeTipoDte($tipoDte);
        return self::DOCUMENT_TYPE_CLASSES[$tipoDte] ?? 'is-default';
    }

    public static function clientPayload(string $moduleKey, array $module, array $preferences): array {
        $columns = [];
        foreach (($module['columnas'] ?? []) as $key => $label) {
            $columns[] = [
                'key' => (string) $key,
                'label' => (string) $label,
                'table' => self::shouldShowColumn($preferences, (string) $key, 'table'),
                'excel' => self::shouldShowColumn($preferences, (string) $key, 'excel'),
            ];
        }

        $documentTypes = [];
        foreach (($preferences['document_types'] ?? []) as $code => $config) {
            if (!is_array($config)) {
                continue;
            }

            $documentTypes[] = [
                'code' => (string) $code,
                'label' => (string) ($config['label'] ?? ('Tipo DTE ' . $code)),
                'show' => !empty($config['show']),
                'highlight' => !empty($config['highlight']),
            ];
        }

        return [
            'module_key' => self::normalizeModuleKey($moduleKey),
            'customized' => !empty($preferences['_customized']),
            'columns' => $columns,
            'document_types' => $documentTypes,
        ];
    }

    private static function getStoredPreferences(PDO $pdo, string $moduleKey, int $userId): ?array {
        $stmt = $pdo->prepare(
            "SELECT preferences_json FROM " . self::TABLE_NAME . " WHERE user_id = :user_id AND module_key = :module_key LIMIT 1"
        );
        $stmt->execute([
            ':user_id' => $userId,
            ':module_key' => self::normalizeModuleKey($moduleKey),
        ]);
        $json = $stmt->fetchColumn();
        if (!is_string($json) || trim($json) === '') {
            return null;
        }

        $decoded = json_decode($json, true);
        return is_array($decoded) ? $decoded : null;
    }

    private static function normalizePreferences(string $moduleKey, array $module, array $payload, array $default, bool $customized): array {
        $availableColumns = array_keys($module['columnas'] ?? []);
        $normalized = $default;
        $normalized['_customized'] = $customized;

        foreach (['table_columns', 'excel_columns'] as $bucket) {
            $incoming = is_array($payload[$bucket] ?? null) ? $payload[$bucket] : [];
            foreach ($availableColumns as $columnKey) {
                if (array_key_exists($columnKey, $incoming)) {
                    $normalized[$bucket][$columnKey] = (bool) $incoming[$columnKey];
                }
            }
        }

        $incomingTypes = is_array($payload['document_types'] ?? null) ? $payload['document_types'] : [];
        foreach ($normalized['document_types'] as $code => $config) {
            if (!is_array($incomingTypes[$code] ?? null)) {
                continue;
            }

            $incoming = $incomingTypes[$code];
            if (array_key_exists('show', $incoming)) {
                $normalized['document_types'][$code]['show'] = (bool) $incoming['show'];
            }
            if (array_key_exists('highlight', $incoming)) {
                $normalized['document_types'][$code]['highlight'] = (bool) $incoming['highlight'];
            }
        }

        return $normalized;
    }

    private static function defaultDocumentTypes(string $moduleKey): array {
        $defaults = [];
        $visibleDefaults = [
            'compras' => ['05'],
            'ventas_consumidor' => ['01', '05', '06'],
            'ventas_contribuyente' => ['03', '05', '06'],
            'retencion_iva' => ['14'],
        ];
        $validTypes = self::moduleDocumentTypes($moduleKey);
        $visible = $visibleDefaults[$moduleKey] ?? $validTypes;

        foreach ($validTypes as $code) {
            $defaults[$code] = [
                'label' => self::DOCUMENT_TYPES[$code] ?? ('Tipo DTE ' . $code),
                'show' => in_array($code, $visible, true),
                'highlight' => $code === '05',
                'color' => $code === '05' ? 'red' : '',
            ];
        }

        return $defaults;
    }

    private static function moduleDocumentTypes(string $moduleKey): array {
        $module = getLibroModule($moduleKey) ?? [];
        $tipos = [];

        if (preg_match_all('/\d+/', (string) ($module['tipos_validos'] ?? ''), $matches) > 0) {
            foreach ($matches[0] as $tipo) {
                $tipos[] = self::normalizeTipoDte($tipo);
            }
        }

        if ($tipos === []) {
            $tipos = array_keys(self::DOCUMENT_TYPES);
        }

        return array_values(array_unique(array_filter($tipos)));
    }

    private static function getDocumentTypeConfig(array $preferences, string $tipoDte): ?array {
        $documentTypes = is_array($preferences['document_types'] ?? null) ? $preferences['document_types'] : [];
        $config = $documentTypes[$tipoDte] ?? null;

        return is_array($config) ? $config : null;
    }

    private static function normalizeModuleKey(string $moduleKey): string {
        $moduleKey = strtolower(trim($moduleKey));
        return preg_replace('/[^a-z0-9_]/', '_', $moduleKey) ?: 'modulo';
    }

    private static function normalizeTipoDte(string $tipoDte): string {
        $tipoDte = trim($tipoDte);
        if ($tipoDte === '') {
            return '';
        }

        return ctype_digit($tipoDte) ? str_pad($tipoDte, 2, '0', STR_PAD_LEFT) : $tipoDte;
    }
}

function getModuleColumnConfig(PDO $pdo, string $moduleKey, int $userId, ?array $module = null): array {
    return ModulePreferenceService::getModuleColumnConfig($pdo, $moduleKey, $userId, $module);
}

function getDefaultColumnConfig(string $moduleKey, array $module): array {
    return ModulePreferenceService::getDefaultColumnConfig($moduleKey, $module);
}

function shouldShowColumn(array $preferences, string $columnKey, string $context): bool {
    return ModulePreferenceService::shouldShowColumn($preferences, $columnKey, $context);
}

function shouldExportColumn(array $preferences, string $columnKey): bool {
    return ModulePreferenceService::shouldShowColumn($preferences, $columnKey, 'excel');
}

function getDocumentTypeLabelForModule(string $moduleKey, string $tipoDte, array $preferences, string $fallback = ''): string {
    return ModulePreferenceService::getDocumentTypeLabelForModule($moduleKey, $tipoDte, $preferences, $fallback);
}

function shouldHighlightDocumentType(string $moduleKey, string $tipoDte, array $preferences): bool {
    return ModulePreferenceService::shouldHighlightDocumentType($moduleKey, $tipoDte, $preferences);
}
