<?php

function getLibroModules(): array {
    return [
        'compras' => [
            'tipo'              => 'compras',
            'nombre'            => 'Libro de Compras',
            'ruta'              => 'pages/compras.php',
            'icono'             => 'icon-layout',
            'accent_color'      => '#4b49ac',
            'descripcion'       => 'Gestiona tus DTE de compras y revisa el libro por periodo.',
            'visible_sidebar'   => true,
            'visible_dashboard' => true,
            'tipos_validos'     => '03, 05 y 06',
            'columnas'          => [
                'no'                        => 'No.',
                'fecha'                     => 'Fecha',
                'numero_control'            => 'N control',
                'nrc'                       => 'NRC',
                'nit'                       => 'NIT',
                'nombre_proveedor'          => 'Nombre del proveedor',
                'ventas_internas'           => 'Internas',
                'ventas_importacion'        => 'Import.',
                'ventas_internas_exentas'   => 'Internas exentas',
                'ventas_importacion_exentas'=> 'Import. exentas',
                'credito_fiscal'            => 'Credito fiscal',
                'total_compras'             => 'Total compras',
                'iva_percibido'             => 'IVA percibido 1%',
                'iva_retenido'              => 'IVA retenido 1%',
                'codigo_generacion'         => 'Codigo de generacion',
                'sello_recepcion'           => 'Sello de recepcion',
                'numero_control_completo'   => 'Numero de control completo',
            ],
            'columnas_numericas' => [
                'ventas_internas',
                'ventas_importacion',
                'ventas_internas_exentas',
                'ventas_importacion_exentas',
                'credito_fiscal',
                'total_compras',
                'iva_percibido',
                'iva_retenido',
            ],
        ],
        'ventas_consumidor' => [
            'tipo'              => 'ventas_consumidor',
            'nombre'            => 'Ventas Consumidor Final',
            'ruta'              => 'pages/ventas_consumidor.php',
            'icono'             => 'icon-grid-2',
            'accent_color'      => '#f59e0b',
            'descripcion'       => 'Trabaja facturas FCF (01) y consolida ventas diarias propias.',
            'visible_sidebar'   => true,
            'visible_dashboard' => true,
            'tipos_validos'     => '01',
            'columnas'          => [
                'no'                           => 'No.',
                'dia_emision'                  => 'Dia',
                'del_numero'                   => 'Del No.',
                'al_numero'                    => 'Al No.',
                'codigo_generacion_desde'      => 'Codigo de generacion del No.',
                'codigo_generacion_hasta'      => 'Codigo de generacion al No.',
                'sello_recepcion'              => 'Sello de recepcion',
                'ventas_exentas'               => 'Ventas exentas',
                'ventas_internas_gravadas'     => 'Ventas internas gravadas',
                'exportaciones'                => 'Exportaciones',
                'total_ventas_diarias_propias' => 'Total ventas diarias propias',
                'ventas_cuenta_terceros'       => 'Ventas a cuenta de terceros',
            ],
            'columnas_numericas' => [
                'ventas_exentas',
                'ventas_internas_gravadas',
                'exportaciones',
                'total_ventas_diarias_propias',
                'ventas_cuenta_terceros',
            ],
        ],
        'ventas_contribuyente' => [
            'tipo'              => 'ventas_contribuyente',
            'nombre'            => 'Ventas a Contribuyentes',
            'ruta'              => 'pages/ventas_contribuyente.php',
            'icono'             => 'icon-briefcase',
            'accent_color'      => '#0f766e',
            'descripcion'       => 'Administra CCF, NC y ND para ventas a contribuyentes.',
            'visible_sidebar'   => true,
            'visible_dashboard' => true,
            'tipos_validos'     => '03, 05 y 06',
            'columnas'          => [
                'no'                                        => 'No.',
                'fecha'                                     => 'Fecha de emision',
                'numero_control_preimpreso'                 => 'N control preimpreso',
                'numero_control_interno'                    => 'N control interno',
                'codigo_generacion'                         => 'Codigo de generacion',
                'nombre_cliente'                            => 'Nombre cliente',
                'nrc_cliente'                               => 'NRC',
                'ventas_exentas_contribuyente'              => 'Exentas',
                'ventas_internas_gravadas_contribuyente'    => 'Internas gravadas',
                'debito_fiscal_contribuyente'               => 'Debito fiscal',
                'ventas_exentas_cuenta_terceros'            => 'Exentas cuenta terceros',
                'ventas_internas_gravadas_cuenta_terceros'  => 'Internas gravadas cuenta terceros',
                'debito_fiscal_cuenta_terceros'             => 'Debito fiscal cuenta terceros',
                'iva_percibido'                             => 'IVA percibido',
                'iva_retenido'                              => 'IVA retenido 1%',
                'ventas_totales'                            => 'Ventas totales',
            ],
            'columnas_numericas' => [
                'ventas_exentas_contribuyente',
                'ventas_internas_gravadas_contribuyente',
                'debito_fiscal_contribuyente',
                'ventas_exentas_cuenta_terceros',
                'ventas_internas_gravadas_cuenta_terceros',
                'debito_fiscal_cuenta_terceros',
                'iva_percibido',
                'iva_retenido',
                'ventas_totales',
            ],
        ],
        'retencion_iva' => [
            'tipo'              => 'retencion_iva',
            'nombre'            => 'Retencion IVA 1%',
            'ruta'              => 'pages/retencion_iva.php',
            'icono'             => 'mdi mdi-shield-check-outline',
            'accent_color'      => '#1d4ed8',
            'descripcion'       => 'Controla comprobantes de retencion DTE 14 por periodo.',
            'visible_sidebar'   => true,
            'visible_dashboard' => true,
            'tipos_validos'     => '14',
            'columnas'          => [
                'no'                     => 'No.',
                'nit_agente_retencion'   => 'NIT del agente de retencion',
                'fecha_emision'          => 'Fecha de emision',
                'tipo_documento'         => 'Tipo doc.',
                'serie_documento'        => 'Serie',
                'numero_documento'       => 'N de documento',
                'monto_sujeto_retencion' => 'Monto sujeto a retencion',
                'retencion_iva_1'        => 'Retencion IVA 1%',
                'dui_agente_retencion'   => 'DUI del agente',
                'numero_anexo'           => 'N anexo',
            ],
            'columnas_numericas' => [
                'monto_sujeto_retencion',
                'retencion_iva_1',
            ],
        ],
    ];
}

function getLibroModule(string $tipo): ?array {
    $modulos = getLibroModules();
    return $modulos[$tipo] ?? null;
}
