<?php

function getPlanCatalog(): array
{
    return [
        [
            'slug' => 'free',
            'nombre' => 'Free',
            'descripcion' => 'Ideal para conocer Zentra antes de contratar un plan.',
            'precio' => 0.00,
            'moneda' => 'USD',
            'periodo' => 'prueba',
            'destacado' => false,
            'personalizado' => false,
            'activo' => true,
            'orden' => 1,
            'limite_empresas' => 1,
            'limite_usuarios' => 1,
            'limite_documentos' => 25,
            'caracteristicas' => [
                ['texto' => '1 empresa de prueba', 'incluido' => true],
                ['texto' => '1 usuario administrador', 'incluido' => true],
                ['texto' => 'Hasta 25 documentos de prueba', 'incluido' => true],
                ['texto' => 'Acceso limitado al dashboard', 'incluido' => true],
                ['texto' => 'Clientes y productos de prueba', 'incluido' => true],
                ['texto' => 'Reportes basicos', 'incluido' => true],
                ['texto' => 'Soporte por correo en 48-72 horas', 'incluido' => true],
                ['texto' => 'Funciones nuevas en evaluacion', 'incluido' => true],
            ],
        ],
        [
            'slug' => 'light',
            'nombre' => 'Light',
            'descripcion' => 'Para emprendedores, contadores pequenos o negocios que estan iniciando.',
            'precio' => 6.99,
            'moneda' => 'USD',
            'periodo' => 'mes',
            'destacado' => false,
            'personalizado' => false,
            'activo' => true,
            'orden' => 2,
            'limite_empresas' => 1,
            'limite_usuarios' => 1,
            'limite_documentos' => 150,
            'caracteristicas' => [
                ['texto' => '1 empresa activa', 'incluido' => true],
                ['texto' => '1 usuario administrador', 'incluido' => true],
                ['texto' => 'Hasta 150 documentos mensuales', 'incluido' => true],
                ['texto' => 'Clientes', 'incluido' => true],
                ['texto' => 'Productos o servicios', 'incluido' => true],
                ['texto' => 'Ventas', 'incluido' => true],
                ['texto' => 'Reportes basicos', 'incluido' => true],
                ['texto' => 'Exportacion a Excel', 'incluido' => true],
                ['texto' => 'Acceso mensual a Zentra', 'incluido' => true],
                ['texto' => 'Soporte por correo en 24-48 horas', 'incluido' => true],
                ['texto' => 'Actualizaciones incluidas', 'incluido' => true],
            ],
        ],
        [
            'slug' => 'pro',
            'nombre' => 'Pro',
            'descripcion' => 'Para negocios en crecimiento que necesitan facturacion, control y reportes mas completos.',
            'precio' => 17.99,
            'moneda' => 'USD',
            'periodo' => 'mes',
            'destacado' => true,
            'personalizado' => false,
            'activo' => true,
            'orden' => 3,
            'limite_empresas' => 3,
            'limite_usuarios' => 3,
            'limite_documentos' => 700,
            'caracteristicas' => [
                ['texto' => 'Hasta 3 empresas/clientes', 'incluido' => true],
                ['texto' => 'Hasta 3 usuarios', 'incluido' => true],
                ['texto' => 'Hasta 700 documentos mensuales', 'incluido' => true],
                ['texto' => 'Facturacion electronica DTE', 'incluido' => true],
                ['texto' => 'Clientes y proveedores', 'incluido' => true],
                ['texto' => 'Ventas y compras', 'incluido' => true],
                ['texto' => 'Inventario basico', 'incluido' => true],
                ['texto' => 'Dashboard avanzado', 'incluido' => true],
                ['texto' => 'Reportes en Excel y PDF', 'incluido' => true],
                ['texto' => 'Roles de usuario', 'incluido' => true],
                ['texto' => 'Soporte prioritario en 12-24 horas', 'incluido' => true],
                ['texto' => 'Funciones nuevas antes de liberacion general', 'incluido' => true],
            ],
        ],
        [
            'slug' => 'ultra',
            'nombre' => 'Ultra',
            'descripcion' => 'Para empresas con operacion mas alta o contadores con varios clientes.',
            'precio' => 34.99,
            'moneda' => 'USD',
            'periodo' => 'mes',
            'destacado' => false,
            'personalizado' => false,
            'activo' => true,
            'orden' => 4,
            'limite_empresas' => 10,
            'limite_usuarios' => 8,
            'limite_documentos' => 2000,
            'caracteristicas' => [
                ['texto' => 'Hasta 10 empresas/clientes', 'incluido' => true],
                ['texto' => 'Hasta 8 usuarios', 'incluido' => true],
                ['texto' => 'Hasta 2,000 documentos mensuales', 'incluido' => true],
                ['texto' => 'Modulo DTE completo', 'incluido' => true],
                ['texto' => 'Ventas', 'incluido' => true],
                ['texto' => 'Compras', 'incluido' => true],
                ['texto' => 'Inventario', 'incluido' => true],
                ['texto' => 'Clientes', 'incluido' => true],
                ['texto' => 'Proveedores', 'incluido' => true],
                ['texto' => 'Cuentas por cobrar', 'incluido' => true],
                ['texto' => 'Cuentas por pagar', 'incluido' => true],
                ['texto' => 'Reportes avanzados', 'incluido' => true],
                ['texto' => 'Exportacion Excel/PDF', 'incluido' => true],
                ['texto' => 'Auditoria de usuarios', 'incluido' => true],
                ['texto' => 'Soporte prioritario', 'incluido' => true],
                ['texto' => 'Mayor capacidad operativa', 'incluido' => true],
                ['texto' => 'Capacitacion inicial basica', 'incluido' => true],
            ],
        ],
        [
            'slug' => 'enterprise',
            'nombre' => 'Enterprise',
            'descripcion' => 'Para empresas que necesitan mas capacidad, mas usuarios o modulos especiales.',
            'precio' => null,
            'moneda' => 'USD',
            'periodo' => 'cotizacion',
            'destacado' => false,
            'personalizado' => true,
            'activo' => true,
            'orden' => 5,
            'limite_empresas' => null,
            'limite_usuarios' => null,
            'limite_documentos' => null,
            'caracteristicas' => [
                ['texto' => 'Empresas ilimitadas o personalizadas', 'incluido' => true],
                ['texto' => 'Usuarios personalizados', 'incluido' => true],
                ['texto' => 'Documentos mensuales personalizados', 'incluido' => true],
                ['texto' => 'Multi-sucursal', 'incluido' => true],
                ['texto' => 'Integraciones API', 'incluido' => true],
                ['texto' => 'Migracion de datos', 'incluido' => true],
                ['texto' => 'Reportes personalizados', 'incluido' => true],
                ['texto' => 'Capacitacion completa', 'incluido' => true],
                ['texto' => 'Soporte tecnico dedicado', 'incluido' => true],
                ['texto' => 'Desarrollo de modulos especiales', 'incluido' => true],
            ],
        ],
    ];
}
