-- PostgreSQL schema for extracted DTE module
-- Source backup analyzed on 2026-06-27
-- This script intentionally excludes original SIETELSA data.
-- Dependency: the main SaaS must already provide public.usuarios(id).

SET client_encoding = 'UTF8';
SET TIME ZONE 'America/El_Salvador';

BEGIN;

CREATE OR REPLACE FUNCTION dte_set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS dte_usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    nombre_completo VARCHAR(150) NULL,
    foto_perfil VARCHAR(255) NULL,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'user',
    estado SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dte_usuarios_username UNIQUE (username),
    CONSTRAINT chk_dte_usuarios_rol CHECK (rol IN ('admin', 'user')),
    CONSTRAINT chk_dte_usuarios_estado CHECK (estado IN (0, 1))
);
CREATE INDEX IF NOT EXISTS idx_dte_usuarios_estado ON dte_usuarios (estado);
CREATE INDEX IF NOT EXISTS idx_dte_usuarios_rol ON dte_usuarios (rol);

CREATE TABLE IF NOT EXISTS dte_user_bridge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    main_user_id INTEGER NOT NULL,
    dte_user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dte_user_bridge_main_user UNIQUE (main_user_id),
    CONSTRAINT uq_dte_user_bridge_dte_user UNIQUE (dte_user_id),
    CONSTRAINT fk_dte_user_bridge_main_user
        FOREIGN KEY (main_user_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_dte_user_bridge_dte_user
        FOREIGN KEY (dte_user_id) REFERENCES dte_usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_dte_user_bridge_main_user ON dte_user_bridge (main_user_id);
CREATE INDEX IF NOT EXISTS idx_dte_user_bridge_dte_user ON dte_user_bridge (dte_user_id);
DROP TRIGGER IF EXISTS trg_dte_user_bridge_updated_at ON dte_user_bridge;
CREATE TRIGGER trg_dte_user_bridge_updated_at
BEFORE UPDATE ON dte_user_bridge
FOR EACH ROW
EXECUTE FUNCTION dte_set_updated_at();

CREATE TABLE IF NOT EXISTS dte_empresas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    iniciales VARCHAR(4) NULL,
    color_emblema VARCHAR(20) NULL DEFAULT '#f97316',
    dui VARCHAR(20) NULL,
    nit VARCHAR(20) NULL,
    nrc VARCHAR(20) NULL,
    tipo_legal VARCHAR(20) NULL DEFAULT 'natural',
    estado SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_vez_usada TIMESTAMP NULL,
    CONSTRAINT chk_dte_empresas_tipo_legal CHECK (tipo_legal IN ('natural', 'juridica')),
    CONSTRAINT chk_dte_empresas_estado CHECK (estado IN (0, 1)),
    CONSTRAINT fk_dte_empresas_usuario
        FOREIGN KEY (id_usuario) REFERENCES dte_usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_dte_empresas_usuario ON dte_empresas (id_usuario);
CREATE INDEX IF NOT EXISTS idx_dte_empresas_estado ON dte_empresas (estado);
CREATE INDEX IF NOT EXISTS idx_dte_empresas_nit ON dte_empresas (nit);
CREATE INDEX IF NOT EXISTS idx_dte_empresas_nrc ON dte_empresas (nrc);

CREATE TABLE IF NOT EXISTS dte_libros (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    mes SMALLINT NOT NULL,
    anio INTEGER NOT NULL,
    nombre VARCHAR(100) GENERATED ALWAYS AS ((tipo || '-' || anio::text || '-' || mes::text)) STORED,
    estado SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dte_libro UNIQUE (id_empresa, tipo, mes, anio),
    CONSTRAINT chk_dte_libros_tipo CHECK (tipo IN ('compras', 'ventas_consumidor', 'ventas_contribuyente', 'retencion_iva')),
    CONSTRAINT chk_dte_libros_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT chk_dte_libros_anio CHECK (anio BETWEEN 2000 AND 9999),
    CONSTRAINT chk_dte_libros_estado CHECK (estado IN (0, 1)),
    CONSTRAINT fk_dte_libros_empresa
        FOREIGN KEY (id_empresa) REFERENCES dte_empresas(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_dte_libros_usuario
        FOREIGN KEY (id_usuario) REFERENCES dte_usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_dte_libros_usuario ON dte_libros (id_usuario);
CREATE INDEX IF NOT EXISTS idx_dte_libros_estado ON dte_libros (estado);

CREATE TABLE IF NOT EXISTS dte_facturas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_libro INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    codigo_generacion VARCHAR(50) NOT NULL,
    sello_recepcion TEXT NULL,
    numero_control VARCHAR(50) NULL,
    tipo_dte VARCHAR(10) NULL,
    fecha DATE NOT NULL,
    nrc VARCHAR(20) NULL,
    nit VARCHAR(20) NULL,
    nombre_proveedor VARCHAR(200) NULL,
    ventas_internas DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ventas_importacion DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ventas_internas_exentas DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ventas_importacion_exentas DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    credito_fiscal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_compras DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    iva_percibido DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    iva_retenido DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    numero_control_completo VARCHAR(100) NULL,
    raw_json TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nombre_cliente VARCHAR(200) NULL,
    nrc_cliente VARCHAR(20) NULL,
    numero_control_preimpreso VARCHAR(50) NULL,
    numero_control_interno VARCHAR(50) NULL,
    dia_emision DATE NULL,
    del_numero INTEGER NULL,
    al_numero INTEGER NULL,
    codigo_generacion_desde VARCHAR(50) NULL,
    codigo_generacion_hasta VARCHAR(50) NULL,
    ventas_exentas DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ventas_internas_gravadas DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    exportaciones DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_ventas_diarias_propias DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ventas_cuenta_terceros DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    debito_fiscal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ventas_exentas_contribuyente DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ventas_internas_gravadas_contribuyente DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    debito_fiscal_contribuyente DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ventas_totales DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    nit_agente_retencion VARCHAR(20) NULL,
    fecha_emision_retencion DATE NULL,
    tipo_documento_relacionado VARCHAR(20) NULL,
    serie_documento VARCHAR(50) NULL,
    numero_documento VARCHAR(50) NULL,
    monto_sujeto_retencion DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    retencion_iva_1 DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    dui_agente_retencion VARCHAR(20) NULL,
    numero_anexo VARCHAR(20) NULL,
    compras_exentas DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    compras_gravadas DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    impuestos_calculados DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    fovial_otros DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    import_batch_id VARCHAR(64) NULL,
    import_index INTEGER NULL,
    source_filename VARCHAR(255) NULL,
    raw_json_hash CHAR(64) NULL,
    posible_duplicado SMALLINT NOT NULL DEFAULT 0,
    fuera_de_periodo SMALLINT NOT NULL DEFAULT 0,
    motivo_no_contabilizado VARCHAR(255) NULL,
    tipo_documento_nombre VARCHAR(100) NULL,
    documento_relacionado_numero_control VARCHAR(100) NULL,
    documento_relacionado_codigo_generacion VARCHAR(100) NULL,
    documento_relacionado_fecha DATE NULL,
    tipo_movimiento SMALLINT NOT NULL DEFAULT 1,
    signo_contable SMALLINT NOT NULL DEFAULT 1,
    es_repetido SMALLINT NOT NULL DEFAULT 0,
    motivo_exclusion VARCHAR(255) NULL,
    contabilizable SMALLINT NOT NULL DEFAULT 1,
    documento_relacionado_tipo VARCHAR(20) NULL,
    documento_relacionado_numero VARCHAR(60) NULL,
    documento_relacionado_codigo VARCHAR(60) NULL,
    CONSTRAINT fk_dte_facturas_libro
        FOREIGN KEY (id_libro) REFERENCES dte_libros(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_dte_facturas_usuario
        FOREIGN KEY (id_usuario) REFERENCES dte_usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_dte_facturas_usuario ON dte_facturas (id_usuario);
CREATE INDEX IF NOT EXISTS idx_dte_facturas_fecha ON dte_facturas (fecha);
CREATE INDEX IF NOT EXISTS idx_dte_facturas_libro ON dte_facturas (id_libro);
CREATE INDEX IF NOT EXISTS idx_dte_facturas_codigo_generacion ON dte_facturas (codigo_generacion);
CREATE INDEX IF NOT EXISTS idx_dte_facturas_raw_json_hash ON dte_facturas (raw_json_hash);

CREATE TABLE IF NOT EXISTS dte_facturas_disponibles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    total INTEGER NOT NULL DEFAULT 50,
    consumidas INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dte_facturas_disponibles_usuario UNIQUE (id_usuario),
    CONSTRAINT fk_dte_facturas_disponibles_usuario
        FOREIGN KEY (id_usuario) REFERENCES dte_usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);
DROP TRIGGER IF EXISTS trg_dte_facturas_disponibles_updated_at ON dte_facturas_disponibles;
CREATE TRIGGER trg_dte_facturas_disponibles_updated_at
BEFORE UPDATE ON dte_facturas_disponibles
FOR EACH ROW
EXECUTE FUNCTION dte_set_updated_at();

CREATE TABLE IF NOT EXISTS dte_user_module_preferences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    module_key VARCHAR(80) NOT NULL,
    preferences_json JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uniq_user_module_preferences UNIQUE (user_id, module_key),
    CONSTRAINT fk_dte_user_module_preferences_user
        FOREIGN KEY (user_id) REFERENCES dte_usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_dte_user_module_preferences_user ON dte_user_module_preferences (user_id);
DROP TRIGGER IF EXISTS trg_dte_user_module_preferences_updated_at ON dte_user_module_preferences;
CREATE TRIGGER trg_dte_user_module_preferences_updated_at
BEFORE UPDATE ON dte_user_module_preferences
FOR EACH ROW
EXECUTE FUNCTION dte_set_updated_at();

COMMIT;
